# Get detections using RGB images
sh_interfaces/YoloConfig yolo_config
sensor_msgs/Image input

---
bool success # Wheter any object was detected

uint8 num_objects
sh_interfaces/Detection2D[] detections