# Get detections using RGB images
sh_interfaces/YoloConfig yolo_config
sensor_msgs/Image input

---
bool success # Wheter any object was detected

int32 num_objects
sh_interfaces/Detection2D[] detections